version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379" #Open temporarily for debugging
    networks:
      - redisnet
  accounts:
    build: ./accounts
    tty: true
    environment:
      - ACCOUNTS_PORT=10203
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "10203:10203"
    depends_on:
      - couchdb
    networks:
      - couchnet
networks:
  redisnet:
