version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379" #Open temporarily for debugging
    networks:
      - redisnet
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    networks:
      - minionet
    environment:
      - MINIO_ACCESS_KEY=ACCESSKEY
      - MINIO_SECRET_KEY=SECRETKEY
    volumes:
      - ./minio:/export
    command: minio server /export
  admin:
    build: ./admin
    tty: true
    environment:
      - ADMIN_PORT=10201
    ports:
      - "10201:10201"
    depends_on:
      - redis
    networks:
      - redisnet
  volunteers:
    build: ./volunteers
    tty: true
    environment:
      - VOLUNTEERS_PORT=10202
      - SECRET=secret
    ports:
      - "10202:10202"
    depends_on:
      - redis
    networks:
      - redisnet
  events:
    build: ./events
    tty: true
    environment:
      - EVENTS_PORT=10203
      - SECRET=secret
      - DEFAULT_SIZE=100
    ports:
      - "10203:10203"
    depends_on:
      - redis
    networks:
      - redisnet
  fileserve:
    build: ./fileserve
    tty: true
    environment:
      - FILESERVE_PORT=10204
      - MINIO_ACCESS_KEY=ACCESSKEY
      - MINIO_SECRET_KEY=SECRETKEY
    networks:
      - minionet
  organisers:
    build: ./organisers
    tty: true
    environment:
      - ORGANISERS_PORT=10205
      - SECRET=secret
    ports:
      - "10205:10205"
    depends_on:
      - redis
    networks:
      - redisnet
  updater:
    build: ./updater
    tty: true
    depends_on:
      - redis
    networks:
      - redisnet
networks:
  redisnet:
  minionet:
